// Generated by CoffeeScript 1.4.0
(function() {
  var Footer, TopBar;

  TopBar = window.zooniverse.controllers.TopBar;

  (new TopBar).el.prependTo('body');

  Footer = window.zooniverse.controllers.Footer;

  (new Footer).el.appendTo('body > .footer > .container');

}).call(this);
