name: Deploy data.galaxyzoo.org

on:
  # Run this workflow on merge (push) to master
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.creds }}

    - name: Upload to blob storage
      id: upload
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload \
            --account-name zooniversestatic \
            --content-cache-control 'public, max-age=60' \
            --container-name '$web' \
            --name 'data.galaxyzoo.org/index.html' \
            --file './index.html'
          rm ./index.html
          az storage blob upload-batch \
            --account-name zooniversestatic \
            --content-cache-control 'public, immutable, max-age=600' \
            --destination '$web/data.galaxyzoo.org' \
            --source ./

  slack_notification:
    name: Send Slack notification
    uses: zooniverse/ci-cd/.github/workflows/slack_notification.yaml@main
    needs: deploy
    if: always()
    with:
      commit_id: ${{ github.sha }}
      job_name: Deploy data.galaxyzoo.org / build
      status: ${{ needs.deploy.result }}
      title: 'data.galaxyzoo.org deploy complete'
      title_link: 'https://data.galaxyzoo.org'
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
