name: Deploy data.galaxyzoo.org

on:
  # Run this workflow on merge (push) to master
  push:
    branches:
      - master

jobs:
  build:
    name: Build data.galaxyzoo.org
    uses: zooniverse/ci-cd/.github/workflows/npm_build.yaml@main
    with:
      commit_id: ${{ github.sha }}
      node_version: 9
      script: 'build'
      output: 'public'

  deploy:
    name: Deploy data.galaxyzoo.org
    uses: zooniverse/ci-cd/.github/workflows/deploy_static.yaml@main
    needs: build
    with:
      source: 'public'
      target: 'zooniverse-static/data.galaxyzoo.org'
    secrets:
      creds: ${{ secrets.AZURE_STATIC_SITES }}

  slack_notification:
    name: Send Slack notification
    uses: zooniverse/ci-cd/.github/workflows/slack_notification.yaml@main
    needs: deploy
    if: always()
    with:
      commit_id: ${{ github.sha }}
      job_name: Deploy data.galaxyzoo.org / build
      status: ${{ needs.deploy.result }}
      title: 'data.galaxyzoo.org deploy complete'
      title_link: 'https://data.galaxyzoo.org'
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
